connection:
  database: covid
  driver: postgresql+psycopg2
  host: localhost
  password: postgres
  port: 5432
  user: postgres

connection_world:
  database: covid_world
  driver: postgresql+psycopg2
  host: localhost
  password: postgres
  port: 5432
  user: postgres

tables:
- salesfacts
- products
- geo
- date
- manufacturer

prep_data:
  func: null

split_data:
  func: split_data
  percent_sample: 0.0001
  percent_train: 0.75
  y: 'Revenue'
