model:
  id: 5e0724a764f94c38b06ee98706c63d97
  models_path: /home/vinicius/Documents/Projetos/Claro/Piloto/experimentacao/data/model
  retrain:
    func: retrain_model
    paramns:
      end_data: 2013-01-01
      target: revenue
predict:
  func: predict
  output:
    path: /home/vinicius/Documents/Projetos/Claro/Piloto/industrializacao/data
  save_func: save_predict
test:
  paramns: {}
  save_func:
  - save_mlflow
  - save_csv
  test_func: test_func
